package net.opentrends.candidate.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Registration service. Represents a row in the &quot;candidate_Registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.opentrends.candidate.model.impl.RegistrationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.opentrends.candidate.model.impl.RegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Registration
 * @see net.opentrends.candidate.model.impl.RegistrationImpl
 * @see net.opentrends.candidate.model.impl.RegistrationModelImpl
 * @generated
 */
public interface RegistrationModel extends BaseModel<Registration> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a registration model instance should use the {@link Registration} interface instead.
     */

    /**
     * Returns the primary key of this registration.
     *
     * @return the primary key of this registration
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this registration.
     *
     * @param primaryKey the primary key of this registration
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the ID of this registration.
     *
     * @return the ID of this registration
     */
    public long getId();

    /**
     * Sets the ID of this registration.
     *
     * @param id the ID of this registration
     */
    public void setId(long id);

    /**
     * Returns the name of this registration.
     *
     * @return the name of this registration
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this registration.
     *
     * @param name the name of this registration
     */
    public void setName(String name);

    /**
     * Returns the email of this registration.
     *
     * @return the email of this registration
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this registration.
     *
     * @param email the email of this registration
     */
    public void setEmail(String email);

    /**
     * Returns the city of this registration.
     *
     * @return the city of this registration
     */
    @AutoEscape
    public String getCity();

    /**
     * Sets the city of this registration.
     *
     * @param city the city of this registration
     */
    public void setCity(String city);

    /**
     * Returns the mobile no of this registration.
     *
     * @return the mobile no of this registration
     */
    @AutoEscape
    public String getMobileNo();

    /**
     * Sets the mobile no of this registration.
     *
     * @param mobileNo the mobile no of this registration
     */
    public void setMobileNo(String mobileNo);

    /**
     * Returns the photo file entry ID of this registration.
     *
     * @return the photo file entry ID of this registration
     */
    public long getPhotoFileEntryId();

    /**
     * Sets the photo file entry ID of this registration.
     *
     * @param photoFileEntryId the photo file entry ID of this registration
     */
    public void setPhotoFileEntryId(long photoFileEntryId);

    /**
     * Returns the resume file entry ID of this registration.
     *
     * @return the resume file entry ID of this registration
     */
    public long getResumeFileEntryId();

    /**
     * Sets the resume file entry ID of this registration.
     *
     * @param resumeFileEntryId the resume file entry ID of this registration
     */
    public void setResumeFileEntryId(long resumeFileEntryId);

    /**
     * Returns the user ID of this registration.
     *
     * @return the user ID of this registration
     */
    public long getUserId();

    /**
     * Sets the user ID of this registration.
     *
     * @param userId the user ID of this registration
     */
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this registration.
     *
     * @return the user uuid of this registration
     * @throws SystemException if a system exception occurred
     */
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this registration.
     *
     * @param userUuid the user uuid of this registration
     */
    public void setUserUuid(String userUuid);

    /**
     * Returns the group ID of this registration.
     *
     * @return the group ID of this registration
     */
    public long getGroupId();

    /**
     * Sets the group ID of this registration.
     *
     * @param groupId the group ID of this registration
     */
    public void setGroupId(long groupId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        net.opentrends.candidate.model.Registration registration);

    @Override
    public int hashCode();

    @Override
    public CacheModel<net.opentrends.candidate.model.Registration> toCacheModel();

    @Override
    public net.opentrends.candidate.model.Registration toEscapedModel();

    @Override
    public net.opentrends.candidate.model.Registration toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
