package net.opentrends.candidate.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.candidate.model.Registration;
import net.opentrends.candidate.service.RegistrationLocalServiceUtil;

/**
 * The extended model base implementation for the Registration service. Represents a row in the &quot;candidate_Registration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegistrationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RegistrationImpl
 * @see net.opentrends.candidate.model.Registration
 * @generated
 */
public abstract class RegistrationBaseImpl extends RegistrationModelImpl
    implements Registration {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a registration model instance should use the {@link Registration} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RegistrationLocalServiceUtil.addRegistration(this);
        } else {
            RegistrationLocalServiceUtil.updateRegistration(this);
        }
    }
}
