package net.opentrends.studentdata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.studentdata.model.StudentDetails;
import net.opentrends.studentdata.service.StudentDetailsLocalServiceUtil;

/**
 * The extended model base implementation for the StudentDetails service. Represents a row in the &quot;StudentData_StudentDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentDetailsImpl
 * @see net.opentrends.studentdata.model.StudentDetails
 * @generated
 */
public abstract class StudentDetailsBaseImpl extends StudentDetailsModelImpl
    implements StudentDetails {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a student details model instance should use the {@link StudentDetails} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StudentDetailsLocalServiceUtil.addStudentDetails(this);
        } else {
            StudentDetailsLocalServiceUtil.updateStudentDetails(this);
        }
    }
}
