package net.opentrends.studentdata.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.opentrends.studentdata.model.StudentMarks;
import net.opentrends.studentdata.service.StudentMarksLocalServiceUtil;

/**
 * The extended model base implementation for the StudentMarks service. Represents a row in the &quot;StudentData_StudentMarks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StudentMarksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StudentMarksImpl
 * @see net.opentrends.studentdata.model.StudentMarks
 * @generated
 */
public abstract class StudentMarksBaseImpl extends StudentMarksModelImpl
    implements StudentMarks {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a student marks model instance should use the {@link StudentMarks} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            StudentMarksLocalServiceUtil.addStudentMarks(this);
        } else {
            StudentMarksLocalServiceUtil.updateStudentMarks(this);
        }
    }
}
